export const catalogIconOptions = [
  { value: 'star', label: '\u2605 Favorito' },
  { value: 'fruit', label: '\uD83C\uDF4E Fruta' },
  { value: 'vegetable', label: '\uD83E\uDD6C Verdura' },
  { value: 'meat', label: '\uD83E\uDD69 Carne' },
  { value: 'cold-cuts', label: '\uD83E\uDD53 Charcuteria' },
  { value: 'fish', label: '\uD83D\uDC1F Pescado' },
  { value: 'milk', label: '\uD83E\uDD5B Lacteos' },
  { value: 'cheese', label: '\uD83E\uDDC0 Queso' },
  { value: 'egg', label: '\uD83E\uDD5A Huevos' },
  { value: 'bread', label: '\uD83E\uDD56 Pan' },
  { value: 'rice', label: '\uD83C\uDF5A Arroz' },
  { value: 'pasta', label: '\uD83C\uDF5D Pasta' },
  { value: 'beans', label: '\uD83E\uDED8 Legumbres' },
  { value: 'oil', label: '\uD83E\uDED2 Aceite' },
  { value: 'sauce', label: '\uD83E\uDED9 Salsas' },
  { value: 'coffee', label: '\u2615 Cafe' },
  { value: 'cocoa', label: '\uD83C\uDF6B Cacao' },
  { value: 'water', label: '\uD83D\uDCA7 Agua' },
  { value: 'bottle', label: '\uD83D\uDCA7 Botella' },
  { value: 'soft-drink', label: '\uD83E\uDD64 Refrescos' },
  { value: 'drink', label: '\uD83E\uDD64 Bebidas' },
  { value: 'juice', label: '\uD83E\uDDC3 Zumo' },
  { value: 'beer', label: '\uD83C\uDF7A Cerveza' },
  { value: 'wine', label: '\uD83C\uDF77 Bodega' },
  { value: 'snack', label: '\uD83E\uDD68 Aperitivos' },
  { value: 'chocolate', label: '\uD83C\uDF6B Chocolate' },
  { value: 'candy', label: '\uD83C\uDF6C Dulces' },
  { value: 'cookie', label: '\uD83C\uDF6A Galletas' },
  { value: 'can', label: '\uD83E\uDD6B Conservas' },
  { value: 'canned', label: '\uD83E\uDD6B Conservas' },
  { value: 'frozen', label: '\uD83E\uDDCA Congelados' },
  { value: 'pizza', label: '\uD83C\uDF55 Pizza' },
  { value: 'detergent', label: '\uD83E\uDDFC Detergente' },
  { value: 'soap', label: '\uD83E\uDDFC Detergente' },
  { value: 'paper', label: '\uD83E\uDDFB Papel' },
  { value: 'clean', label: '\uD83E\uDDFD Limpieza' },
  { value: 'hygiene', label: '\uD83E\uDDF4 Higiene' },
  { value: 'hair-care', label: '\uD83E\uDDF4 Cuidado capilar' },
  { value: 'makeup', label: '\uD83D\uDC84 Maquillaje' },
  { value: 'first-aid', label: '\uD83E\uDE79 Parafarmacia' },
  { value: 'supplement', label: '\uD83D\uDC8A Suplementos' },
  { value: 'eye-care', label: '\uD83D\uDC41 Ojos' },
  { value: 'condom', label: '\uD83D\uDEE1 Proteccion' },
  { value: 'repellent', label: '\uD83E\uDD9F Repelente' },
  { value: 'antiseptic', label: '\uD83E\uDDEA Antiseptico' },
  { value: 'bandage', label: '\uD83E\uDE79 Curas' },
  { value: 'cotton', label: '\u2601 Algodon' },
  { value: 'baby', label: '\uD83C\uDF7C Bebe' },
  { value: 'diaper', label: '\uD83E\uDDF7 Panales' },
  { value: 'care', label: '\uD83E\uDDF4 Cuidado' },
  { value: 'pet', label: '\uD83D\uDC3E Mascotas' },
  { value: 'tomato', label: '\uD83C\uDF45 Tomate' },
  { value: 'potato', label: '\uD83E\uDD54 Patata' },
  { value: 'onion', label: '\uD83E\uDDC5 Cebolla' },
  { value: 'garlic', label: '\uD83E\uDDC4 Ajo' },
  { value: 'banana', label: '\uD83C\uDF4C Platano' },
  { value: 'citrus', label: '\uD83C\uDF4A Citricos' },
  { value: 'cart', label: '\uD83D\uDED2 General' },
  { value: 'shopping-basket', label: '\uD83D\uDED2 General' },
] as const;

export function catalogIconLabel(iconKey: string): string {
  return catalogIconOptions.find((option) => option.value === iconKey)?.label ?? catalogIconOptions[catalogIconOptions.length - 1].label;
}

export function categoryOptionLabel(category: { name: string; iconKey: string }): string {
  return `${catalogIconLabel(category.iconKey).split(' ')[0]} ${category.name}`;
}
